"""Generate the manuscript's single main table from stored results only.

Round-5 reviewer item 20.P0.2 asks that the fallback fraction and the observed
collision rates sit *next to* the statistical coverage results, so that no
reader can take G1/G2/G3 validity for collision safety.  This script therefore
emits one two-panel ``table*``:

* panel (a) --- the certified statistical layer, read from
  ``results/exp1_validity.json`` (G1 and G3) and ``results/exp7_budget.json``
  (G2);
* panel (b) --- the uncertified operational layer of the fresh anchored study,
  read from ``results/window_anchor_v1_study/summary.json``.

Every printed number is computed here; none is typed by hand.  The generated
block is spliced into ``paper/root.tex`` between the AUTO-TABLE markers.

Usage::

    python code/make_main_table.py            # rewrite the block in root.tex
    python code/make_main_table.py --check    # fail if root.tex is stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEX = ROOT / "paper/root.tex"
BEGIN = "% BEGIN AUTO-TABLE tab:main (generated by code/make_main_table.py)\n"
END = "% END AUTO-TABLE tab:main\n"

EXP1 = ROOT / "results/exp1_validity.json"
EXP7 = ROOT / "results/exp7_budget.json"
FRESH = ROOT / "results/window_anchor_v1_study/summary.json"

# (summary key, crowd label, G1 construction label, tracking bound label)
CELLS = (
    ("sf|cs|track=0.00m", "Social Force", "mixture", "0.00"),
    ("sf|spending_cs|track=0.00m", "Social Force", "spending", "0.00"),
    ("sf|cs|track=0.10m", "Social Force", "mixture", "0.10"),
    ("sf|spending_cs|track=0.10m", "Social Force", "spending", "0.10"),
    ("orca|cs|track=0.00m", "ORCA-lite", "mixture", "0.00"),
    ("orca|spending_cs|track=0.00m", "ORCA-lite", "spending", "0.00"),
    ("orca|cs|track=0.10m", "ORCA-lite", "mixture", "0.10"),
    ("orca|spending_cs|track=0.10m", "ORCA-lite", "spending", "0.10"),
)

# panel (b) percentage columns, in print order
FRESH_COLS = (
    "finite_radius_containment_violation_fraction",
    "active_window_fallback_fraction",
    "selected_agent_fraction_over_attempted_window_agents",
    "endpoint_implication_active_control_fraction",
    "observed_collision_episode_fraction",
)


def pct(x: float) -> str:
    """One-decimal percent, matching the convention of the reviewed revision."""
    return f"{100.0 * float(x):.1f}"


def one_dp(x: float) -> str:
    return f"{float(x):.1f}"


def thousands(n: int) -> str:
    return f"{n:,}".replace(",", "{,}")


def coverage_rows() -> list[tuple[str, str, str, str, str]]:
    """(contract, construction, rate at 0.05, rate at 0.1, verdict)."""
    exp1 = json.loads(EXP1.read_text())
    exp7 = json.loads(EXP7.read_text())

    cs = {(r["beta"], r["delta"]): r["anytime_undercoverage_rate"]
          for r in exp1["cs_time_uniform"]}
    plug = {(r["beta"], r["delta_nominal"]): r["anytime_undercoverage_rate"]
            for r in exp1["plugin_time_uniform"]}
    g2 = {(r["eps"], r["delta_prime"]): r["anytime_exceed_rate"]
          for r in exp7["synthetic"]}
    ep = {r["delta"]: r for r in exp1["episode_level"]}

    def verdict(a: float, b: float) -> str:
        return "yes" if (a <= 0.05 and b <= 0.10) else "\\textbf{no}"

    rows: list[tuple[str, str, str, str, str]] = []
    g1 = "\\textbf{G1} $\\Prob(\\exists w\\!: r_w\\!<\\!q_\\beta)$"
    for i, beta in enumerate((0.9, 0.95)):
        a, b = cs[(beta, 0.05)], cs[(beta, 0.1)]
        rows.append((g1 if i == 0 else "\\quad(same event)",
                     f"CS (ours), $\\beta{{=}}{beta:g}$", pct(a), pct(b), verdict(a, b)))
    a, b = plug[(0.9, 0.05)], plug[(0.9, 0.1)]
    rows.append(("\\quad(same event)", "plug-in split-CP, $\\beta{=}0.9$",
                 pct(a), pct(b), verdict(a, b)))
    g2lab = ("\\textbf{G2} $\\Prob(\\exists W\\!: \\sum_w\\hat Y_w\\!>\\!B_W)$"
             " ($\\delta'$ part)")
    for i, eps in enumerate((0.05, 0.1)):
        a, b = g2[(eps, 0.05)], g2[(eps, 0.1)]
        rows.append((g2lab if i == 0 else "\\quad(same event)",
                     f"CS boundary, $\\epsilon{{=}}{eps:g}$", pct(a), pct(b), verdict(a, b)))
    g3lab = "\\textbf{G3} $\\Prob(\\exists w\\!\\le\\! W\\!: s_w\\!>\\!r_w)$"
    for i, (key, name) in enumerate((("auc_episode_viol", "AUC"),
                                     ("aucb_episode_viol", "AUC-B"),
                                     ("union_episode_viol", "fixed-$T$ Union CP"))):
        a, b = ep[0.05][key], ep[0.1][key]
        rows.append((g3lab if i == 0 else "\\quad(same event)", name,
                     pct(a), pct(b), verdict(a, b)))
    return rows


def operational_rows() -> list[str]:
    fresh = json.loads(FRESH.read_text())["cells"]
    out = []
    for key, crowd, ctor, mtr in CELLS:
        c = fresh[key]
        vals = [pct(c[f]) for f in FRESH_COLS] + [one_dp(c["mean_path_length_m"])]
        out.append(" & ".join([crowd, ctor, mtr] + vals) + "\\\\")
    return out


def total_controls() -> tuple[int, int]:
    """(total attempts, total controls) read from the stored per-attempt records."""
    study = json.loads(FRESH.read_text())
    n_att = int(study["n_completed_attempts"])
    steps = set()
    for path in sorted((ROOT / "results/window_anchor_v1_study/attempts").glob("*.json")):
        steps.add(int(json.loads(path.read_text())["record"]["steps"]))
    assert len(steps) == 1, f"attempts disagree on control count: {sorted(steps)}"
    return n_att, n_att * steps.pop()


def render() -> str:
    cov = coverage_rows()
    ops = operational_rows()
    n_att, n_ctl = total_controls()
    fresh = json.loads(FRESH.read_text())["cells"]
    fb = [fresh[k[0]]["active_window_fallback_fraction"] for k in CELLS]
    coll = [fresh[k[0]]["observed_collision_episode_fraction"] for k in CELLS]
    n_ep = sum(fresh[k[0]]["n_episodes"] for k in CELLS)
    n_win = sum(fresh[k[0]]["n_attempted_windows"] for k in CELLS)
    per_cell = fresh[CELLS[0][0]]["n_episodes"]

    L: list[str] = []
    L.append("\\begin{table*}[!tb]")
    L.append("\\centering")
    L.append("\\scriptsize")
    L.append("\\setlength{\\tabcolsep}{3.5pt}")
    L.append("\\renewcommand{\\arraystretch}{0.92}")
    L.append("\\caption{Coverage contracts and the operational outcome, in one place.}")
    L.append("\\label{tab:main}")
    L.append("\\begin{tabular}{llrrc}")
    L.append("\\toprule")
    L.append("\\multicolumn{5}{l}{\\textbf{(a) Certified statistical layer.}"
             " Measured failure rate (\\%), i.i.d.\\ controls.}\\\\")
    L.append("Certified event & Construction & $0.05$ & $0.1$ & Holds?\\\\")
    L.append("\\midrule")
    for contract, ctor, a, b, ok in cov:
        L.append(f"{contract} & {ctor} & {a} & {b} & {ok}\\\\")
    L.append("\\bottomrule")
    L.append("\\end{tabular}")
    L.append("")
    L.append("\\vspace{3pt}")
    L.append("")
    L.append("\\sbox0{%")
    L.append("\\begin{tabular}{llrrrrrrr}")
    L.append("\\toprule")
    L.append("\\multicolumn{9}{l}{\\textbf{(b) Uncertified operational layer.}"
             " The same interface run end to end: fresh anchored study, $%s$ episodes"
             " ($%s$/cell).}\\\\" % (thousands(n_ep), thousands(per_cell)))
    L.append("Crowd & G1 construction & $m_{\\rm tr}$ (m) & $V$ (\\%) & FB (\\%) & Sel. (\\%)"
             " & End. (\\%) & Coll. (\\%) & Path (m)\\\\")
    L.append("\\midrule")
    L.extend(ops)
    L.append("\\bottomrule")
    L.append("\\end{tabular}}\\usebox0")
    L.append("")
    L.append("\\vspace{2pt}")
    L.append("")
    L.append("\\begin{minipage}{\\wd0}\\scriptsize")
    L.append("(a) Confidence $0.05$ and $0.1$ is $\\delta$, and $\\delta'$ on the G2 row: that row"
             " measures only the count boundary's own allocation, so the deployed G2 event"
             " $\\Prob(\\exists W\\!: V_W\\!>\\!B_W)$ costs the total $\\delta+\\delta'$"
             " (Theorem~\\ref{thm:budget}). A row \\emph{holds}"
             " when its measured rate is at or below that target."
             " (b) \\texttt{window\\_anchor\\_v1}: $%s$ windows and $%s$ controls, all attempted"
             " records retained." % (thousands(n_win), thousands(n_ctl)))
    L.append("$V$: finite-radius containment violations. FB: fallback over active controls"
             " (five warm-up controls excluded). Sel.: selected stable UID/window-agent."
             " End.: controls carrying the selected-agent discrete endpoint implication."
             " Coll.: episodes with an observed collision. Path: mean path length.")
    L.append("\\emph{Read the two panels together.} Every contract in (a) holds at its target, yet in"
             " (b) fallback covers $%s$--$%s\\%%$ of active controls and $%s$--$%s\\%%$ of episodes"
             " still record a collision: statistical validity is not collision safety."
             " Panel (b) is simulated descriptive evidence and not a deployment-safety claim;"
             " $%s$ episodes per cell leave wide Wilson intervals."
             % (pct(min(fb)), pct(max(fb)), pct(min(coll)), pct(max(coll)),
                thousands(per_cell)))
    L.append("\\end{minipage}")
    L.append("\\end{table*}")
    return "\n".join(L) + "\n"


def splice(text: str, block: str) -> str:
    assert text.count(BEGIN) == 1, "missing/duplicated AUTO-TABLE begin marker"
    assert text.count(END) == 1, "missing/duplicated AUTO-TABLE end marker"
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return head + BEGIN + block + END + tail


def current_block(text: str) -> str:
    return text.split(BEGIN, 1)[1].split(END, 1)[0]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify root.tex already carries the generated block")
    args = ap.parse_args()
    block = render()
    text = TEX.read_text()
    if args.check:
        if BEGIN not in text or END not in text:
            print("FAIL make_main_table: AUTO-TABLE markers missing from root.tex")
            return 1
        if current_block(text) != block:
            print("FAIL make_main_table: root.tex table is stale; rerun without --check")
            return 1
        print("PASS make_main_table: root.tex main table matches stored results")
        return 0
    TEX.write_text(splice(text, block))
    print(f"wrote main table into {TEX} ({len(block.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
