"""Generate the paper-facing ledger for the locked 2026-09-08 study."""

from __future__ import annotations

import json
import os
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results" / "review_round2"
PAPER = ROOT / "paper"
FAMILIES = ("attribution", "search_test", "long_horizon",
            "warehouse_resolution", "stale", "independent_planner")


def read_json(path: Path) -> dict:
    return json.loads(path.read_text())


def atomic_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(content)
    os.replace(tmp, path)


def group(summary: dict, family: str, label: str) -> dict:
    return summary["families"][family]["by_label"][label]


def all_records() -> list[dict]:
    rows = []
    for family in FAMILIES:
        for path in sorted((RESULTS / family).glob("*.json")):
            if path.name not in {"summary.json", "sensitivity.json"}:
                rows.append(read_json(path))
    return rows


def render() -> tuple[str, str]:
    summary = read_json(RESULTS / "summary.json")
    manifest = read_json(RESULTS / "manifest.json")
    sensitivity = read_json(RESULTS / "warehouse_resolution" /
                            "sensitivity.json")
    if not summary["complete"] or manifest["status"] != "PASS":
        raise RuntimeError("round-two evidence is incomplete or unaudited")

    records = all_records()
    if len(records) != manifest["n_trace_records"]:
        raise RuntimeError("trace-record count disagrees with manifest")

    def mean(label: str, family: str = "attribution") -> float:
        return group(summary, family, label)["throughput_mean"]

    g2 = [r["guidance"] for r in records
          if r["condition"]["family"] == "attribution"
          and r["condition"]["label"].startswith("fluid_g2_")]
    g0 = [r["guidance"] for r in records
          if r["condition"]["family"] == "attribution"
          and r["condition"]["label"].startswith("fluid_g0_")]
    # Guidance metadata repeat over simulator seeds; maxima are unaffected.
    stale_events = [e for r in records
                    if r["condition"]["family"] == "stale"
                    and r["condition"]["label"] == "stale"
                    for e in r["update_events"]]
    stale_delays = [e["applied_at_step"] - e["requested_at_step"]
                    for e in stale_events]
    deployment = {}
    for label in ("frozen", "synchronous", "stale"):
        vals = [r["deployment_timing_model"]["completed_tasks_per_wall_s"]
                for r in records if r["condition"]["family"] == "stale"
                and r["condition"]["label"] == label]
        deployment[label] = sum(vals) / len(vals)

    random_means = [mean(f"fluid_g2_random{i}") for i in range(3)]
    search = summary["search"]
    long_groups = summary["families"]["long_horizon"]["by_map_label"]
    warehouse_means = [mean(f"K{k}", "warehouse_resolution")
                       for k in (32, 64, 128, 256)]
    maze_toll_rows = [r for r in records
                      if r["condition"]["family"] == "long_horizon"
                      and r["condition"]["map"] == "maze-32-32-4"
                      and r["condition"]["label"] == "tolls"]
    sync_rows = [r for r in records
                 if r["condition"]["family"] == "stale"
                 and r["condition"]["label"] == "synchronous"]
    macros = [
        "% AUTOGENERATED by code/make_review_round2_paper.py -- do not edit.",
        rf"\newcommand{{\RTwoTraceRecords}}{{{len(records)}}}",
        rf"\newcommand{{\RTwoArtifacts}}{{{len(manifest['artifacts'])}}}",
        rf"\newcommand{{\RTwoGoalEvents}}{{{sum(r['completed'] for r in records):,}}}",
        rf"\newcommand{{\RTwoPeakRSSMiB}}{{{max(r['process_peak_rss_bytes_so_far'] for r in records) / 2**20:.1f}}}",
        rf"\newcommand{{\RTwoSeedOnly}}{{{mean('seed_mild_1p5'):.3f}}}",
        rf"\newcommand{{\RTwoGTwoLane}}{{{mean('fluid_g2_lane'):.3f}}}",
        rf"\newcommand{{\RTwoGTwoSym}}{{{mean('fluid_g2_symmetric'):.3f}}}",
        rf"\newcommand{{\RTwoGTwoRandomLo}}{{{min(random_means):.3f}}}",
        rf"\newcommand{{\RTwoGTwoRandomHi}}{{{max(random_means):.3f}}}",
        rf"\newcommand{{\RTwoGZeroSym}}{{{mean('fluid_g0_symmetric'):.3f}}}",
        rf"\newcommand{{\RTwoGZeroLane}}{{{mean('fluid_g0_lane'):.3f}}}",
        rf"\newcommand{{\RTwoGTwoFactorMax}}{{{max(x['linear_factor_bound'] for x in g2):.6f}}}",
        rf"\newcommand{{\RTwoGZeroFactorMax}}{{{max(x['linear_factor_bound'] for x in g0):.6f}}}",
        rf"\newcommand{{\RTwoSearchCandidates}}{{{search['n_training_candidates']}}}",
        rf"\newcommand{{\RTwoSearchTest}}{{{mean('validation_selected', 'search_test'):.3f}}}",
        rf"\newcommand{{\RTwoSearchTerminalValidation}}{{{sum(search['terminal_mean_validation_runs']) / len(search['terminal_mean_validation_runs']):.3f}}}",
        rf"\newcommand{{\RTwoWorstTail}}{{{min(x['last_half_over_whole_mean'] for x in long_groups.values()):.3f}}}",
        rf"\newcommand{{\RTwoCollapseRuns}}{{{sum(x['collapse_runs'] for x in long_groups.values())}}}",
        rf"\newcommand{{\RTwoMazeTollTailQuantile}}{{{sum(r['trace_metrics']['task_delay_steps']['p99'] for r in maze_toll_rows) / len(maze_toll_rows):.0f}}}",
        rf"\newcommand{{\RTwoWarehouseTputLo}}{{{min(warehouse_means):.3f}}}",
        rf"\newcommand{{\RTwoWarehouseTputHi}}{{{max(warehouse_means):.3f}}}",
        rf"\newcommand{{\RTwoStaleFrozen}}{{{mean('frozen', 'stale'):.3f}}}",
        rf"\newcommand{{\RTwoStaleSync}}{{{mean('synchronous', 'stale'):.3f}}}",
        rf"\newcommand{{\RTwoStaleAsync}}{{{mean('stale', 'stale'):.3f}}}",
        rf"\newcommand{{\RTwoDeployFrozen}}{{{deployment['frozen']:.2f}}}",
        rf"\newcommand{{\RTwoDeploySync}}{{{deployment['synchronous']:.2f}}}",
        rf"\newcommand{{\RTwoDeployStale}}{{{deployment['stale']:.2f}}}",
        rf"\newcommand{{\RTwoStaleDelayLo}}{{{min(stale_delays)}}}",
        rf"\newcommand{{\RTwoStaleDelayHi}}{{{max(stale_delays)}}}",
        rf"\newcommand{{\RTwoSyncPause}}{{{sum(r['resolve_and_rebuild_s'] for r in sync_rows) / len(sync_rows):.2f}}}",
        rf"\newcommand{{\RTwoWPPUnweighted}}{{{mean('unweighted', 'independent_planner'):.3f}}}",
        rf"\newcommand{{\RTwoWPPLanes}}{{{mean('lanes', 'independent_planner'):.3f}}}",
        rf"\newcommand{{\RTwoWPPTolls}}{{{mean('tolls', 'independent_planner'):.3f}}}",
        rf"\newcommand{{\RTwoWarehouseCorrMin}}{{{min(x['pearson_to_K256'] for x in sensitivity.values()):.3f}}}",
        rf"\newcommand{{\RTwoWarehouseLTwoMax}}{{{max(x['relative_l2_to_K256'] for x in sensitivity.values()):.3f}}}",
        "",
    ]

    def long_cell(map_name: str, label: str) -> str:
        cell = summary["families"]["long_horizon"]["by_map_label"][
            f"{map_name}::{label}"]
        return f"{cell['throughput_mean']:.3f} ({cell['last_half_over_whole_mean']:.3f})"

    table = [
        "% AUTOGENERATED by code/make_review_round2_paper.py -- do not edit.",
        r"\begin{table}[t]",
        r"\caption{Locked fresh-seed 5,000-step results in our PIBT-style stack. Entries are mean tasks/step (mean last-half/whole ratio), three seeds. No row is a steady-state or native-planner claim.}",
        r"\label{tab:roundtwo}",
        r"\centering\scriptsize",
        r"\setlength{\tabcolsep}{2.6pt}",
        r"\begin{tabular}{lccc}",
        r"\toprule",
        r"Map@agents & unweighted & lanes & tolls \\",
        r"\midrule",
        (f"empty@400 & {long_cell('empty-32-32', 'unweighted')} & "
         f"{long_cell('empty-32-32', 'lanes')} & "
         f"{long_cell('empty-32-32', 'tolls')} " + r"\\"),
        (f"maze@310 & {long_cell('maze-32-32-4', 'unweighted')} & "
         f"{long_cell('maze-32-32-4', 'lanes')} & "
         f"{long_cell('maze-32-32-4', 'tolls')} " + r"\\"),
        (f"warehouse@800 & "
         f"{long_cell('warehouse-10-20-10-2-1', 'unweighted')} & "
         f"{long_cell('warehouse-10-20-10-2-1', 'lanes')} & "
         f"{long_cell('warehouse-10-20-10-2-1', 'tolls')} " + r"\\"),
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]
    return "\n".join(macros), "\n".join(table)


def main() -> None:
    macros, table = render()
    atomic_text(PAPER / "review_round2_numbers.tex", macros)
    atomic_text(PAPER / "review_round2_table.tex", table)
    print("generated review_round2_numbers.tex and review_round2_table.tex")


if __name__ == "__main__":
    main()
