"""Emit `paper/native_check_numbers.tex` from the scored native planner check.

Every macro below is read straight out of `results/native_check/summary_bench.json`, which
`analyze_native_check.py` writes from the 600 retained native runs under the hash-locked
benchmark protocol.  Nothing is typed by hand.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(os.path.dirname(HERE))
PROJ = os.path.dirname(os.path.dirname(HERE))
NC = os.path.join(os.path.dirname(os.path.dirname(HERE)), "results", "native_check")
OUT = os.path.join(os.path.dirname(os.path.dirname(HERE)), "paper", "native_check_numbers.tex")


def main():
    S = json.load(open(os.path.join(NC, "summary_bench.json")))
    C = S["criteria"]
    cells = {(c["map"], c["N"]): c for c in S["cells"]}
    room170, room270 = cells[("room-32-32-4", 170)], cells[("room-32-32-4", 270)]
    diag = json.load(open(os.path.join(NC, "diag_tau_ablation.json")))
    dg = {(d["N"], d["tau"]): d for d in diag["summary"]}
    lines = ["% AUTOGENERATED by code/native/make_native_macros.py -- do not edit."]

    def m(name, val):
        lines.append(f"\\newcommand{{\\{name}}}{{{val}}}")

    m("NCRuns", S["native_cells"])
    m("NCSeeds", S["seeds"])
    m("NCSteps", S["steps"])
    m("NCCommit", S["lacam3_commit"])
    m("NCSha", S["protocol_sha256"][:12])
    m("NCCriteriaPassed", S["n_criteria_passed"])
    m("NCCriteriaTotal", len(C))
    m("NCSignTU", C["C1_sign_tolls_vs_unweighted"]["value"])
    m("NCSignTL", C["C2_sign_tolls_vs_lanes"]["value"])
    m("NCLevel", f"{100 * C['C3_level']['value']:.1f}")
    m("NCTie", C["C5_tie_rule"]["value"])
    m("NCRoomOneSevenTU", f"{room170['d_TU_native']:+.2f}")
    m("NCRoomOneSevenTUOurs", f"{room170['d_TU_python']:+.2f}")
    m("NCRoomTwoSevenTU", f"{room270['d_TU_native']:+.2f}")
    m("NCRoomTwoSevenTUOurs", f"{room270['d_TU_python']:+.2f}")
    m("NCRoomOneSevenTolls", f"{room170['native_tolls']:.2f}")
    m("NCRoomOneSevenUnw", f"{room170['native_unweighted']:.2f}")
    emp = cells[("empty-32-32", 400)]
    m("NCEmptyFourTU", f"{emp['d_TU_native']:+.2f}")
    m("NCEmptyFourTUOurs", f"{emp['d_TU_python']:+.2f}")
    wh = cells[("warehouse-10-20-10-2-1", 400)]
    m("NCWhFourTU", f"{wh['d_TU_native']:+.2f}")
    m("NCWhFourTUOurs", f"{wh['d_TU_python']:+.2f}")
    m("NCTauBaseTU", f"{dg[(170, 20)]['d_TU']:+.2f}")
    m("NCTauOffTU", f"{dg[(170, 0)]['d_TU']:+.2f}")
    m("NCTauSeeds", diag["seeds"])
    # ---- round-4 items 17.P1.1 / 17.P0.1: the tie-resolution mechanism ------------------------
    # eps_tie is the resolution at which a native PIBT sees the guidance. Following the guidance
    # MORE precisely is the decisive test: if coarse binning caused the native reversal, the toll
    # advantage would come back. Numbers from results/checks/tie_resolution.json.
    tr_path = os.path.join(PROJ, "results", "checks", "tie_resolution.json")
    if os.path.exists(tr_path):
        with open(tr_path) as fh:
            tr = json.load(fh)
        op, ob, al = tr["open_map_only"], tr["obstacle_maps_only"], tr["all_cells"]
        m("NCTieEpsFine", f"{tr['eps_fine']:g}")
        m("NCTieEpsCoarse", f"{tr['eps_coarse']:g}")
        m("NCTieOpenCells", op["n_cells"])
        m("NCTieOpenWorse", op["n_fine_worse"])
        m("NCTieOpenMin", f"{op['min_effect']:+.2f}")
        m("NCTieOpenMax", f"{op['max_effect']:+.2f}")
        m("NCTieObsCells", ob["n_cells"])
        m("NCTieObsWorse", ob["n_fine_worse"])
        m("NCTieObsMin", f"{ob['min_effect']:+.2f}")
        m("NCTieObsMax", f"{ob['max_effect']:+.2f}")
        m("NCTieObsMean", f"{ob['mean_effect']:+.2f}")
        m("NCTieObsSig", ob["n_ci_excludes_zero"])
        m("NCTieAllSig", al["n_ci_excludes_zero"])
        m("NCTieAllCells", al["n_cells"])
        room = next(r for r in tr["cells"] if r["map"] == "room-32-32-4" and r["N"] == 170)
        m("NCTieRoomCoarse", f"{room['d_TU_coarse']['mean']:+.2f}")
        m("NCTieRoomFine", f"{room['d_TU_fine']['mean']:+.2f}")
        # ---- round-5 item 17.P1.2: implementation-local ties vs model-level mismatch -----------
        # d_TU(coarse) = d_TU(fine) + (coarse - fine).  The first term is what the fluid field is
        # worth once the planner follows it (model level); the second is what quantizing a
        # noninteger distance table is worth (implementation level), and any noninteger field
        # earns it.  Both are per-cell paired means over the same frozen native runs.
        m("NCSepObsModelNeg", ob["n_model_term_negative"])
        m("NCSepObsModelMean", f"{ob['mean_model_term']:+.2f}")
        m("NCSepObsModelMin", f"{ob['min_model_term']:+.2f}")
        m("NCSepObsModelMax", f"{ob['max_model_term']:+.2f}")
        m("NCSepObsBinMean", f"{ob['mean_tiebin_term']:+.2f}")
        m("NCSepObsBinMin", f"{ob['min_tiebin_term']:+.2f}")
        m("NCSepObsBinMax", f"{ob['max_tiebin_term']:+.2f}")
        m("NCSepOpenModelPos", op["n_model_term_positive"])
        m("NCSepOpenModelMean", f"{op['mean_model_term']:+.2f}")
        m("NCSepOpenBinMean", f"{op['mean_tiebin_term']:+.2f}")
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(lines) - 1} macros)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
